POST http://localhost:3000/user
Content-Type: application/json

{
    "email": "miguel12105marcos@gmail.com",
    "password": "12345678"
}

###
PUT http://localhost:3000/user/validation
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjM3NjM1NiwiZXhwIjoxNzQyMzgzNTU2fQ.Im1mNZWg_5Uvk3iRnHaa0BUbOk0Nk_9-IUAm1xo8Jig

{
    "code": "3efe8c"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "miguel12105marcos@gmail.com",
    "password": "12345678"
}

###
PATCH http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjM3NjQ4MSwiZXhwIjoxNzQyMzgzNjgxfQ.UGlRW2-CAjRLqpVkjAVphKQaqcLEs94-D0nBIXRK91g

{
    "name" : "John Doe",
    "lastname" : "Doe",
    "nif" : "12345678Z"
}
}