POST http://localhost:3000/user
Content-Type: application/json

{
    "email": "john.doe@gmail.com",
    "password": "12345678"
}

###
PUT http://localhost:3000/user/validation
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2QyYzI5N2JhZTBjN2E3NGY0NDdkNjIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MTg2NTYyMywiZXhwIjoxNzQxODcyODIzfQ.SjyJ1xrd_wyM3e-MiSbbSyCz3FxZey-kaCxAW_EI63A

{
    "code": "595f0f"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "john.doe@gmail.com",
    "password": "12345678"
}

###
PATCH http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2QyYzI5N2JhZTBjN2E3NGY0NDdkNjIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MTg2NzQ1MiwiZXhwIjoxNzQxODc0NjUyfQ.PyDxHuS6s6cW0pd2j0OB8LRM_HRHcN2GZzXLzzVv1AA

{
    "name" : "John Doe",
    "lastname" : "Doe",
    "nif" : "12345678Z"
}